apply plugin: 'java'
apply plugin: 'com.google.protobuf'

group 'com.ford.demo'

version '1.0-SNAPSHOT'

buildscript {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath 'com.google.protobuf:protobuf-gradle-plugin:0.9.4'
    }
}

dependencies {
    // gRPC dependencies:
    // Dependency for gRPC, using Netty for network communication.
    implementation 'io.grpc:grpc-netty-shaded:1.58.0'
    // Dependency for gRPC's Protocol Buffer
    implementation 'io.grpc:grpc-protobuf:1.58.0'
    // Dependency for gRPC stubs
    implementation 'io.grpc:grpc-stub:1.58.0'

    // Protobuf dependency:
    // Core Java library for Google Protocol Buffers.
    // this helps up to generate code in java
    implementation 'com.google.protobuf:protobuf-java:3.24.0'

    // Other dependencies:
    implementation 'javax.annotation:javax.annotation-api:1.3.2'
}

// protobuf plugin - protoc compiler and related plugin behaviour setup
protobuf {
    // Configure the Protoc compiler
    protoc {
        // this version of protoc will be used for protoc compiler in tasks.
        artifact = "com.google.protobuf:protoc:3.24.0"
    }
    // Define Protobuf plugins that protoc should use.
    plugins {
        // Define the gRPC plugin for protoc. This plugin generates gRPC
        // service interfaces and stubs from your .proto service definitions.
        grpc {
            // Specify the artifact coordinates for the gRPC protoc plugin.
            artifact = 'io.grpc:protoc-gen-grpc-java:1.58.0'
        }
    }
    // Configure how proto generation tasks should behave.
    generateProtoTasks {
        // Apply the following configuration to all proto generation tasks.
        all()*.plugins {
            // For each task, enable the 'grpc' plugin. This ensures that
            // both Protobuf message classes and gRPC service classes are generated.
            grpc {}
        }
    }
}

// setting up paths for sources
// when we run protoc we will be getting two different set of data
// In grpc path we will get the service java files for extention
// In java path we will get the artifacts and its related builder classes
sourceSets {
    main {
        java {
            srcDirs 'build/generated/source/proto/main/grpc'
            srcDirs 'build/generated/source/proto/main/java'
        }
    }
}
