syntax = "proto3";

option java_multiple_files = true;
option java_package = "com.ford.demo.grpc";

service Greeter {
  rpc SayHello (HelloRequest) returns (HelloReply) {}
}

message HelloRequest {
  string name = 1;
}

message HelloReply {
  string message = 1;
}

service TestGreeter {
  rpc SayHello1 (HelloRequest1) returns (HelloReply1) {}
}

message HelloRequest1 {
  string name = 1;
}

message HelloReply1 {
  string message = 1;
}

service FordGrpcDemo {
  rpc SayFord (requestFord) returns (responseFord) {}
}

message requestFord {
  string name = 1;
}

message responseFord {
  string message = 1;
}